version: "3.9"

services:

  mongo-service:
    image: mongo
    #restart: always
    container_name:  mitocode-mongo-service
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mitocode
      MONGO_INITDB_ROOT_PASSWORD: mitocode
    networks:
      - mitocode

  mongo-express:
    image: mongo-express
    #restart: always
    container_name: mitocode-mongo-express-service
    depends_on:
      - "mongo-service"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mitocode
      ME_CONFIG_MONGODB_ADMINPASSWORD: mitocode
      ME_CONFIG_MONGODB_URL: mongodb://mitocode:mitocode@mongo-service:27017
      ME_CONFIG_BASICAUTH: false
    networks:
      - mitocode

  prometheus:
    image: prom/prometheus
    # network_mode: host
    container_name: mitocode-prometheus
    ports:
      - 9099:9090
    volumes:
      - ./prometheus/config/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mitocode

  grafana:
      image: grafana/grafana-oss
      container_name: mitocode-grafana
      ports:
        - 3000:3000
      volumes:
        - ./grafana:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_SERVER_DOMAIN=localhost
      networks:
        - mitocode

  loki:
      image: grafana/loki
      ports:
        - 3100:3100
      container_name: mitocode-loki
      networks:
        - mitocode

networks:
  mitocode:
    name: mitocode-network