version: "4.26"

services:

  mongo-service:
    image: mongo
    #restart: always
    container_name:  mitocode-mongo-service
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mitocode
      MONGO_INITDB_ROOT_PASSWORD: mitocode
    networks:
      - mitocode

  mongo-express:
    image: mongo-express
    #restart: always
    container_name: mitocode-mongo-express-service
    depends_on:
      - "mongo-service"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mitocode
      ME_CONFIG_MONGODB_ADMINPASSWORD: mitocode
      ME_CONFIG_MONGODB_URL: mongodb://mitocode:mitocode@mongo-service:27017
    networks:
      - mitocode

networks:
  mitocode:
    name: mitocode-network