scrape_configs:

  - job_name: 'User Service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.0.3:9004']
        labels:
          application: 'User Service Microservice'

  - job_name: 'Product Service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.0.3:9002']
        labels:
          application: 'Product Service Microservice'